# Generated by Django 6.0.6 on 2026-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=255)),
                ('parent_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.CharField(max_length=100)),
                ('dt_turnover', models.DateField(blank=True, null=True)),
                ('ct_turnover', models.DateField(blank=True, null=True)),
                ('client_type', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('balance_equivalent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('card_system', models.CharField(max_length=50)),
                ('card_status', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=10)),
                ('head_office', models.CharField(blank=True, max_length=255, null=True)),
                ('id_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('resident_status', models.CharField(max_length=10)),
                ('client_full_name', models.CharField(max_length=255)),
                ('row_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'active_cards',
                'indexes': [models.Index(fields=['account'], name='active_card_account_c7afcf_idx'), models.Index(fields=['branch_code'], name='active_card_branch__1137d2_idx')],
            },
        ),
    ]
