# Generated by Django 6.0.6 on 2026-06-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField()),
                ('total_cards', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceStatisticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('total_cards', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchDashboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_office', models.CharField(max_length=255)),
                ('total_cards', models.BigIntegerField()),
                ('active_cards', models.BigIntegerField()),
                ('active_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BranchDashboardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardCategoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardTypeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.BigIntegerField()),
                ('active_cards', models.BigIntegerField()),
                ('active_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noactive_cards', models.BigIntegerField()),
                ('noactive_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('virtual_cards_count', models.BigIntegerField()),
                ('virtual_cards_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uzs_total_balance', models.DecimalField(decimal_places=3, max_digits=30)),
                ('uzs_average_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('uzs_cards_count', models.BigIntegerField()),
                ('usd_total_balance', models.DecimalField(decimal_places=8, max_digits=30)),
                ('usd_average_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usd_cards_count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpireCardsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeadOfficeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_days', models.IntegerField()),
                ('total_active_cards', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyIssuedCardsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPeriodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('cards_count', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='analiz_tablitsa.activityperiodreport')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceStatisticsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('cards_count', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='analiz_tablitsa.balancestatisticsreport')),
            ],
        ),
        migrations.CreateModel(
            name='BranchCardTypeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
                ('total', models.BigIntegerField()),
                ('active', models.BigIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_types', to='analiz_tablitsa.branchdashboarditem')),
            ],
        ),
        migrations.CreateModel(
            name='BranchBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzs', models.DecimalField(decimal_places=2, max_digits=30)),
                ('usd', models.DecimalField(decimal_places=2, max_digits=30)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='analiz_tablitsa.branchdashboarditem')),
            ],
        ),
        migrations.AddField(
            model_name='branchdashboarditem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='analiz_tablitsa.branchdashboardreport'),
        ),
        migrations.CreateModel(
            name='BranchDormantStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uzs_cards', models.BigIntegerField()),
                ('usd_cards', models.BigIntegerField()),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dormant', to='analiz_tablitsa.branchdashboarditem')),
            ],
        ),
        migrations.CreateModel(
            name='CardCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('cards_count', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='analiz_tablitsa.cardcategoryreport')),
            ],
        ),
        migrations.CreateModel(
            name='CardStatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_status', models.CharField(max_length=100)),
                ('cards_count', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_status_statistics', to='analiz_tablitsa.analyticsreport')),
            ],
        ),
        migrations.CreateModel(
            name='CardTypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
                ('cards_count', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('systems', models.JSONField(default=list)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_types', to='analiz_tablitsa.cardtypestatistics')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(max_length=100)),
                ('cards_count', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_type_statistics', to='analiz_tablitsa.analyticsreport')),
            ],
        ),
        migrations.CreateModel(
            name='ExpireCardsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('count', models.BigIntegerField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expire_statistics', to='analiz_tablitsa.expirecardsreport')),
            ],
        ),
        migrations.CreateModel(
            name='HeadOfficeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_office', models.CharField(max_length=255)),
                ('active_cards', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_offices', to='analiz_tablitsa.headofficeactivity')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyIssuedCardsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('cards_count', models.BigIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_cards', to='analiz_tablitsa.monthlyissuedcardsreport')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_status', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('cards_count', models.BigIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_statistics', to='analiz_tablitsa.analyticsreport')),
            ],
        ),
    ]
